Repository media-service-dev/process, pull requests merged in 2020-07, with the labels that each got.

#65 Add support for detached process spawn
  src/Process/Process.ts
  src/Process/ProcessOptions.ts
Labels: enhancement

#67 Fix wait for detached process
  src/Process/Process.ts
  src/Process/ProcessStatus.ts
Labels: bug

#69 Add shell cache
  src/Process/Process.ts
Labels: enhancement

#68 Fix missing dots in doc blocks
  src/Process/Process.ts
  src/Process/ProcessOptions.ts
Labels: chore, documentation

#71 Fix lodash vulnerability
  yarn.lock
Labels: security
